### ISSUE TITLE
Support for OpenNebula 5

### ISSUE THREAD

**Issue by jose-sanchezm** [indigo-dc/onedock#67] opened 2017-01-31 10:47 UTC
Hello, l'm trying to generate a Vagrant image based on the one already provided but updated to Ubuntu Xenial and Docker 1.13 with CRIU in order to develop the migration functionality. The work done so far is in the migration branch in this same repository.
OpenNebula and Docker seem to install just fine but not onedock. When doing a vagrant up, the following messages appear at the end of the process:

```
==> default: Cloning into 'onedock'...
==> default: Failed to open TCP connection to localhost:2633 (Connection refused - connect(2) for "localhost" port 2633)
==> default: OpenNebula DATASTORE name not found, use the ID instead
==> default: option datastore: Parsing error
==> default: Failed to open TCP connection to localhost:2633 (Connection refused - connect(2) for "localhost" port 2633)
==> default: invalid option: -n
==> default: User and Password for oneadmin user:
```

however, doing vagrant ssh works and I can execute commands correctly. I've seen that the oned.conf file has been updated as expected but the onedock datastore is not present so I've tried to add it manually to find this error:

```
oneadmin@ubuntu-xenial:~$ cat > onedock.ds << EOF
>          NAME=onedock
>          DS_MAD=onedock
>          TM_MAD=onedock
> EOF
oneadmin@ubuntu-xenial:~$ onedatastore create onedock.ds
[DatastoreAllocate] DS_MAD named "onedock" is not defined in oned.conf
```

Could you please have a look at it and guide me about what's missing, please?

Thank you
Best regards.

**Comment by dealfonso** [comment] 2017-01-31 11:23
Hi,

onedock has been tested in ONE 5, but the problem is the automated installation which is only valid for ONE 4. We are including this information in the documentation.

**Comment by hathagat** [comment] 2017-02-03 10:03
Hi, I have a similar problem. You said automated installation is not possible for OpenNebula 5, so I tried the [manual way](https://indigo-dc.gitbooks.io/onedock/content/doc/install-ubuntu.html). I added `onedock` to `TM_MAD` and `DATASTORE_MAD` in `oned.conf`. Nevertheless I get the same error: `[DatastoreAllocate] DS_MAD named "onedock" is not defined in oned.conf`.
How can I fix this?
Thanks in adnvance!

**Comment by dealfonso** [comment] 2017-02-06 11:37
Hi @hathagat and @jose-sanchezm 

there is a branch called one5. I have just updated the branch to integrate onedock with ONE 5.2. I have tested it integrating a fresh ONE 5.2 installation of ONE with the current version of ONEDock.

Can you please test it?

**Comment by hathagat** [comment] 2017-02-16 14:13
Hi @dealfonso,

the datastore creation issue seems to be fixed in branch one5, thank you!
Unfortunately I'm not able to deploy an image in the onedock datastore successfully. Every new image stays in `locked` status for serveral minutes. Afterwards the status switches to `error`.
`Thu Feb 16 16:50:30 2017 : Error copying image in the datastore: Error pushing tag <myserver>:5000/dockerimage:6`
Local docker repository is up and running (docker push etc. are working).
The `RESTRICTED_DIRS` value of the onedock datastore is set properly.

Do you have any ideas?

**Comment by dealfonso** [comment] 2017-03-02 15:58
Hi @hathagat 

the name of the host <myserver> is configured? are you hiding it intentionally?

**Comment by hathagat** [comment] 2017-03-03 11:18
Hi @dealfonso,
yes, the name is configured. The Log message is something like `Error pushing tag 192.168.178.1:5000/dockerimage:6`.

**Comment by dealfonso** [comment] 2017-03-06 14:23
Hi @hathagat , are you able to push the images to your registry by hand from the internal nodes? (I mean, using the docker push command).

**Comment by hathagat** [comment] 2017-03-08 09:07
Hi @dealfonso, pushing and pulling images to the local registry is working.

**Comment by dealfonso** [comment] 2017-03-08 09:17
Hi, @hathagat, i mean to the 192.168.178.1 registry

**Comment by hathagat** [comment] 2017-03-08 10:10
So do I.^^ The registry is fine. One week ago I started using Rancher and Rancher is using this registry, too.

**Comment by dealfonso** [comment] 2017-03-08 10:18
It is hard for me to guess what is happening. Could you please include the configuration files?

**Comment by hathagat** [comment] 2017-03-17 13:17
For testing purposes I did a fresh install of OpenNebula 4 and ONEDock is working as expected now.  Thanks for your support!

**Comment by alpegon** [comment] 2017-03-27 08:25
Opennebula 5 supported ! 
Check the script ```install-onedock-one5``` at the folders ```install/ubuntu``` and ```install/centos```.
In a few days the adapted packages will be released.

**Closed as completed by alpegon** 2017-03-27 08:25 UTC
Labels: enhancement
