### ISSUE TITLE
Error creating a new onedock image from PATH

### ISSUE THREAD

**Issue by alvarosimon** [indigo-dc/onedock#5] opened 2015-12-03 13:42 UTC
Hi

This is a very nice plugin for ONE :smile:, unfortunately I was not able to download a image, the datastore is there but if you follow the documentation example:

> $ cat > ubuntu-docker.tmpl << EOF
> NAME="ubuntu"
> PATH=docker://rastasheep/ubuntu-sshd
> TYPE=OS
> DESCRIPTION="Ubuntu Trusty with SSHd"
> EOF
> $ oneimage create -d onedock ubuntu-docker.tmpl

you get an image in error state:

> ERROR="Thu Dec  3 13:31:45 2015 : Error copying image in the datastore: Error pulling   rastasheep/"

and checking the logs you can see:

> Thu Dec  3 13:31:45 2015 [Z0][ImM][E]: cp: Command "docker pull   rastasheep/" failed: repository name component must match "[a-z0-9](?:-*[a-z0-9])_(?:[._][a-z0-9](?:-_[a-z0-9])_)_"

That is not correct, the `PATH` is not parsed correctly, it should be:
`docker pull   rastasheep/ubuntu-sshd`

Is this an known issue?

Thanks in advance!
Alvaro

**Comment by dealfonso** [comment] 2015-12-03 16:45
Hi, I am trying to reproduce the error, but it is working for me... which version of OpenNebula are you using? and which OS? Please check also the file /var/log/onedock.log.

**Comment by alvarosimon** [comment] 2015-12-04 07:43
Hi Carlos

I'm using the latest OpenNebula version in my tests `4.14.2-2` and CentOS 7. The installation of docker and ONE went fine, I have created the DS, the only problem that I found was the `PATH` image parsing. I can debug a bit `onedock.sh` to know what's going on, it seems that `build_dock_name` function is only returning one value.

**Comment by alvarosimon** [comment] 2015-12-04 08:08
Some extra info, here is the base64 code that I get from ONE, probably cp script is not parsing correctly the values (or something has changed in this version)

`Command execution fail: /var/lib/one/remotes/datastore/onedock/cp PERTX0RSSVZFUl9BQ1RJT05fREFUQT48SU1BR0U+PElEPjE3PC9JRD48VUlEPjA8L1VJRD48R0lEPjA8L0dJRD48VU5BTUU+b25lYWRtaW48L1VOQU1FPjxHTkFNRT5vbmVhZG1pbjwvR05BTUU+PE5BTUU+dWJ1bnR1LXNzaGQ8L05BTUU+PFBFUk1JU1NJT05TPjxPV05FUl9VPjE8L09XTkVSX1U+PE9XTkVSX00+MTwvT1dORVJfTT48T1dORVJfQT4wPC9PV05FUl9BPjxHUk9VUF9VPjA8L0dST1VQX1U+PEdST1VQX00+MDwvR1JPVVBfTT48R1JPVVBfQT4wPC9HUk9VUF9BPjxPVEhFUl9VPjA8L09USEVSX1U+PE9USEVSX00+MDwvT1RIRVJfTT48T1RIRVJfQT4wPC9PVEhFUl9BPjwvUEVSTUlTU0lPTlM+PFRZUEU+MDwvVFlQRT48RElTS19UWVBFPjA8L0RJU0tfVFlQRT48UEVSU0lTVEVOVD4wPC9QRVJTSVNURU5UPjxSRUdUSU1FPjE0NDkyMTU5MDM8L1JFR1RJTUU+PFNPVVJDRT48IVtDREFUQVtdXT48L1NPVVJDRT48UEFUSD48IVtDREFUQVtkb2NrZXI6Ly9yYXN0YXNoZWVwL3VidW50dS1zc2hkXV0+PC9QQVRIPjxGU1RZUEU+PCFbQ0RBVEFbXV0+PC9GU1RZUEU+PFNJWkU+MDwvU0laRT48U1RBVEU+NDwvU1RBVEU+PFJVTk5JTkdfVk1TPjA8L1JVTk5JTkdfVk1TPjxDTE9OSU5HX09QUz4wPC9DTE9OSU5HX09QUz48Q0xPTklOR19JRD4tMTwvQ0xPTklOR19JRD48VEFSR0VUX1NOQVBTSE9UPi0xPC9UQVJHRVRfU05BUFNIT1Q+PERBVEFTVE9SRV9JRD4xMDA8L0RBVEFTVE9SRV9JRD48REFUQVNUT1JFPm9uZWRvY2s8L0RBVEFTVE9SRT48Vk1TPjwvVk1TPjxDTE9ORVM+PC9DTE9ORVM+PFRFTVBMQVRFPjxERVNDUklQVElPTj48IVtDREFUQVtVYnVudHUgVHJ1c3R5IHdpdGggU1NIZF1dPjwvREVTQ1JJUFRJT04+PERFVl9QUkVGSVg+PCFbQ0RBVEFbaGRdXT48L0RFVl9QUkVGSVg+PC9URU1QTEFURT48U05BUFNIT1RTPjwvU05BUFNIT1RTPjwvSU1BR0U+PERBVEFTVE9SRT48SUQ+MTAwPC9JRD48VUlEPjA8L1VJRD48R0lEPjA8L0dJRD48VU5BTUU+b25lYWRtaW48L1VOQU1FPjxHTkFNRT5vbmVhZG1pbjwvR05BTUU+PE5BTUU+b25lZG9jazwvTkFNRT48UEVSTUlTU0lPTlM+PE9XTkVSX1U+MTwvT1dORVJfVT48T1dORVJfTT4xPC9PV05FUl9NPjxPV05FUl9BPjA8L09XTkVSX0E+PEdST1VQX1U+MTwvR1JPVVBfVT48R1JPVVBfTT4wPC9HUk9VUF9NPjxHUk9VUF9BPjA8L0dST1VQX0E+PE9USEVSX1U+MDwvT1RIRVJfVT48T1RIRVJfTT4wPC9PVEhFUl9NPjxPVEhFUl9BPjA8L09USEVSX0E+PC9QRVJNSVNTSU9OUz48RFNfTUFEPjwhW0NEQVRBW29uZWRvY2tdXT48L0RTX01BRD48VE1fTUFEPjwhW0NEQVRBW29uZWRvY2tdXT48L1RNX01BRD48QkFTRV9QQVRIPjwhW0NEQVRBWy92YXIvbGliL29uZS8vZGF0YXN0b3Jlcy8xMDBdXT48L0JBU0VfUEFUSD48VFlQRT4wPC9UWVBFPjxESVNLX1RZUEU+MDwvRElTS19UWVBFPjxTVEFURT4wPC9TVEFURT48Q0xVU1RFUl9JRD4tMTwvQ0xVU1RFUl9JRD48Q0xVU1RFUj48L0NMVVNURVI+PFRPVEFMX01CPjEwMjI4PC9UT1RBTF9NQj48RlJFRV9NQj44MDk5PC9GUkVFX01CPjxVU0VEX01CPjIxMzA8L1VTRURfTUI+PElNQUdFUz48L0lNQUdFUz48VEVNUExBVEU+PEJBU0VfUEFUSD48IVtDREFUQVsvdmFyL2xpYi9vbmUvL2RhdGFzdG9yZXMvXV0+PC9CQVNFX1BBVEg+PENMT05FX1RBUkdFVD48IVtDREFUQVtTWVNURU1dXT48L0NMT05FX1RBUkdFVD48RElTS19UWVBFPjwhW0NEQVRBW0ZJTEVdXT48L0RJU0tfVFlQRT48RFNfTUFEPjwhW0NEQVRBW29uZWRvY2tdXT48L0RTX01BRD48TE5fVEFSR0VUPjwhW0NEQVRBW1NZU1RFTV1dPjwvTE5fVEFSR0VUPjxUTV9NQUQ+PCFbQ0RBVEFbb25lZG9ja11dPjwvVE1fTUFEPjwvVEVNUExBVEU+PC9EQVRBU1RPUkU+PC9EU19EUklWRVJfQUNUSU9OX0RBVEE+ 17`

**Comment by dealfonso** [comment] 2015-12-04 08:24
Hi, thank you for your help. I am preparing an environment to test what is happening. The "cp" script is working in ubuntu. In fact, if I run you exact command, it behaves as expected... I am debugging it in centos, in a while.

**Comment by alvarosimon** [comment] 2015-12-04 08:32
Hi Carlos
More info, I was debugging cp script just to know the return values:

> 38 PROTOCOL=${SRC::9}
> 39 echo $SRC > /tmp/src.out
> 40 echo $DS_TYPE > /tmp/ds_type.out
> 41 echo $PROTOCOL > /tmp/protocol.out
> 42 if [ "$PROTOCOL" == "docker://" ]; then
> 43     SRC=${SRC:9}
> 44     split_dock_name "$SRC" SERVER USER IMAGE TAG
> 45     echo "SERVER:$SERVER USER:$USER IMAGE:$IMAGE TAG:$TAG" > /tmp/split_dock_name.out
> 46 
> 47     DOCKNAME=$(build_dock_name "$SERVER" "$USER" "$IMAGE" "$TAG")
> 48     onedock_exec_and_log "docker pull $DOCKNAME" "Error pulling $DOCKNAME"
> 49 else

I get these values:

> [oneadmin@localhost tmp]$ cat protocol.out 
> docker://
> [oneadmin@localhost tmp]$ cat ds_type.out 
> 0
> [oneadmin@localhost tmp]$ cat split_dock_name.out 
> SERVER:  rastasheep USER: IMAGE: TAG:

I see a space before server name, image name is missing, so it seems a issue within `split_dock_name` function. btw I'm using the current `master` branch.

**Comment by dealfonso** [comment] 2015-12-04 10:45
@alvarosimon could you please check the changes in onedock.sh file included in commit 73560d0bbdacbb02906591075484a5ae389832ac ? I think that the problem is solved (at least in a fresh centos 7).

**Comment by alvarosimon** [comment] 2015-12-04 10:59
@dealfonso perfect! :smile: the issue is fixed with the new commit:

> $ oneimage list
> ID USER       GROUP      NAME            DATASTORE     SIZE TYPE PER STAT RVMS
> 22 oneadmin   oneadmin   ubuntu-sshd     onedock         0M OS    No rdy     0

This issue can be closed, I will continue testing onedock features, Thanks a lot!!

**Comment by dealfonso** [comment] 2015-12-04 11:05
Now it is merged in #6. Thank you for testing it!

**Closed as completed by dealfonso** 2015-12-04 11:05 UTC
Labels: bug
